### ISSUE TITLE
Include semantically meaningful colorcet colormap names

### ISSUE THREAD

**Issue by anntzer** [tlambert03/cmap#10]
* cmap version: 0.0.2
* Python version: any
* Operating System: any

### Description

The colorcet names `colorcet:CET_<letter><number>` are not particularly memorable.  There are some aliases available, which are listed both on the colorcet python package (e.g. "bgy", "bgyw", etc.), and also, if you want a more "official" source for the names, in Peter Kovesi's colorcet.m (http://www.peterkovesi.com/matlabfns/Colourmaps/colorcet.m : "Some colour maps have alternate names for convenience and readability." -- also note that the matlab code effectively makes the colormap names case-insensitive, but I guess lowercase reads nicer).  It would be nice to have these aliases available.  Thanks!

### What I Did

N/A

**Comment by tlambert03** [comment]
Thanks @anntzer.  Colorcet aliases have been added and they will show up in the docs now too:

<img width="706" alt="Screen Shot 2023-05-06 at 10 39 23 AM" src="https://user-images.githubusercontent.com/1609449/236633538-f52ac7a1-67c1-4dd3-8a72-6c8edb07e2f0.png">

note that you'll need to use the fully qualified name to access them ,e.g. `Colormap('colorcet:worb')` instead of `Colormap('worb')`
