### ISSUE TITLE
Contributing with additional colormaps

### ISSUE THREAD

**Issue by apcamargo** [tlambert03/cmap#62]
### Description

I've created a few colormaps for scientific figures over the years using `viscm` and wanted to have them available somehow. Are you planning to allow individual contributions? I haven't made any of these colormaps available in a package, and I think others might also have their own colormaps they'd be willing to share.

I was planning to submit a PR with one of mine, but I noticed that your naming scheme includes the source of the colormap (e.g., `crameri`, `matlab`, etc.). How should I handle this?

If you're open to external contributions, it would be helpful to have a few guidelines (e.g., including a screenshot in the PR, submitting one colormap per PR, etc.).

**Comment by tlambert03** [comment]
Sure, you're the first to ask.  I'm definitely open to it.  We could perhaps create a new namespace, called either `contrib` or we could just add it to the `cmap` namespace (which currently just houses the primary colors, but was my current "misc" namespace).  Do you have thoughts there?  I guess I slightly prefer `contrib` since it makes it clearer that it was an external contribution, as opposed to something that `cmap` itself came up with.

A couple other notes:
- currently, authors are bound to namespaces, not individual colormaps.  So while the `contrib` namespace could have many authors, the connection between author and colormap would only appear perhaps in the little blurb on the website.
- similarly, the license is for the whole namespace, so contributors would have to be ok with that.

Alternatively, I would be happy to let contributors create their own namespaces, but probably less keen to create new namespaces for contributions of one or two items... and would prefer a bulk `contrib` space for that.  Seem reasonable?

let me know if you like that idea, of have any suggestions, and then I can make a PR that creates the namespace and includes some basic documentation/guidelines on how to contribute

**Comment by apcamargo** [comment]
I also prefer having a `contrib` namespace

> currently, authors are bound to namespaces, not individual colormaps. So while the contrib namespace could have many authors, the connection between author and colormap would only appear perhaps in the little blurb on the website.

I think this is fine. Maybe we can have this information in the docstring (which would be pulled to the website)?

> similarly, the license is for the whole namespace, so contributors would have to be ok with that.

Also fine with me.

A bit out of topic, I assume you don't have MatLab's Parula because of the licensing?

**Comment by tlambert03** [comment]
> A bit out of topic, I assume you don't have MatLab's Parula because of the licensing?

correct

**Comment by apcamargo** [comment]
I guess that we can close this :)

One last question: how do you usually determine the licensing? I'm planning to submit PRs with the [Okabe-Ito](https://jfly.uni-koeln.de/color/) and [Observable10](https://d3js.org/d3-scale-chromatic/categorical#schemeObservable10) categorical palettes, but none have obvious licenses. The Okabe-Ito was described in a website [that is now offline](http://jfly.iam.u-tokyo.ac.jp/color/), and the authors didn't mention any license. Observable10 is described in a [blog post](https://observablehq.com/blog/crafting-data-colors), but I couldn't find any license (the repository's only license is for the ColorBrewer's palettes).

**Comment by tlambert03** [comment]
i just merged Okabe-Ito, if a colormap is discussed somewhere online, made freely available, and isn't obviously associated with a commercial product (like parula & Matlab), then I'm happy to just include it lacking a license (it will appear as "UKNOWN") and then remove it if asked.
